/**
 * What can be set on this chart? — the agent's option catalogue.
 *
 * `describe_graph` tells an agent what a graph currently draws. This answers the question before
 * that one: which of the plot options actually reach the drawing on a given chart kind, and
 * what value to send. Without it an agent has only `setGraphOptions(patch)`, into which it must
 * guess field names, and a wrong guess is an ignored key and a silent no-op.
 *
 * The data comes from rendering. `optionCatalog.json` is generated by setting each field,
 * rebuilding the scene, rendering it, and comparing the drawing. So "works on
 * heatmap" means the option was observed to change the picture — not that a control exists, and
 * not that it writes to the document. It is regenerated whenever an option or chart kind is added.
 *
 * Note: what it does not know is whether a value is sensible, how two options interact, and
 * anything about an option whose prerequisite the generator could not set up (the `untestable`
 * list). It reports those as such rather than guessing.
 */
import catalog from "./optionCatalog.json" with { type: "json" };

interface RawOption {
  /** Index into `groups`. */
  g: number;
  /** A value that demonstrably changed the drawing. */
  ex: unknown;
  /** Indices into `kinds` where setting this changes the drawing. */
  k: number[];
  /** Kind index → the working value, where it differs from `ex`. */
  byKind?: Record<string, unknown>;
  /** Kind indices where it is drawn but has no control in the app (agent-only). */
  nc?: number[];
}

interface RawCatalog {
  note: string;
  kinds: string[];
  groups: string[];
  options: Record<string, RawOption>;
  deadEverywhere: string[];
  untestable: string[];
}

const DATA = catalog as unknown as RawCatalog;

/** `path :: type` → the path alone. Only the text before the first " :: " is the path. */
const pathOf = (entry: string): string => entry.split(" :: ")[0]!.trim();

/**
 * Compare group names ignoring case and punctuation.
 *
 * Several groups are named `Kind style — HeatmapStyle` with an em dash. An exact match makes
 * that name hard to type in practice: a filter written as "Kind style ▸ HeatmapStyle" would
 * return no options at all and look exactly like "this kind has no style block". Normalising
 * every run of non-alphanumerics to one space accepts the em dash, a hyphen, or nothing at all,
 * without loosening into substring matching (which would quietly fold "Axis" and "Axis fonts"
 * together).
 */
const normalizeGroup = (s: string): string =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

export interface CatalogOption {
  option: string;
  group: string;
  /** A value known to change the drawing on this kind — send it as-is to check the wiring. */
  example: unknown;
  /** True when the app offers no control for it here: an agent can set it, a user cannot. */
  agentOnly?: boolean;
}

export interface DescribeOptionsResult {
  ok: boolean;
  kind?: string;
  /** How many options match before `limit` is applied. */
  total: number;
  options: CatalogOption[];
  truncated?: boolean;
  groups?: string[];
  error?: string;
  knownKinds?: string[];
  note?: string;
}

export interface DescribeOptionsQuery {
  kind: string;
  /** Restrict to one group, e.g. "Axis", "Series", "Fonts". Case-insensitive. */
  group?: string;
  /** Substring match on the option path, case-insensitive. */
  search?: string;
  limit?: number;
}

/** Every chart kind the catalogue has measurements for. */
export function catalogKinds(): string[] {
  return [...DATA.kinds];
}

/** The option groups, for filtering. */
export function catalogGroups(): string[] {
  return [...DATA.groups];
}

/**
 * The options that reach the drawing on `kind`, with a value known to work there.
 *
 * Sorted by group then path, so a long reply reads in the same order as the Inspector rather
 * than in whatever order the measurement happened to visit them.
 */
export function describeOptions(query: DescribeOptionsQuery): DescribeOptionsResult {
  const kindIndex = DATA.kinds.indexOf(query.kind);
  if (kindIndex < 0) {
    return {
      ok: false,
      total: 0,
      options: [],
      error: `unknown chart kind '${query.kind}'`,
      knownKinds: catalogKinds(),
    };
  }

  const group = query.group === undefined ? undefined : normalizeGroup(query.group);
  const search = query.search?.toLowerCase();

  const matched: CatalogOption[] = [];
  for (const [option, raw] of Object.entries(DATA.options)) {
    if (!raw.k.includes(kindIndex)) continue;
    const groupName = DATA.groups[raw.g] ?? "";
    if (group !== undefined && normalizeGroup(groupName) !== group) continue;
    if (search !== undefined && !option.toLowerCase().includes(search)) continue;
    // A per-kind exception wins over the shared example — some options need a different value
    // on some kinds.
    const example = raw.byKind?.[String(kindIndex)] ?? raw.ex;
    matched.push({
      option,
      group: groupName,
      example,
      ...(raw.nc?.includes(kindIndex) ? { agentOnly: true } : {}),
    });
  }

  matched.sort((a, b) => a.group.localeCompare(b.group) || a.option.localeCompare(b.option));

  const limit = query.limit;
  const capped = limit !== undefined && limit >= 0 && matched.length > limit ? matched.slice(0, limit) : matched;

  return {
    ok: true,
    kind: query.kind,
    total: matched.length,
    options: capped,
    ...(capped.length < matched.length ? { truncated: true } : {}),
    groups: [...new Set(matched.map((o) => o.group))].sort(),
    note:
      "Each option changes the drawing on this kind (measured by rendering, not by having a " +
      "control). `example` is a value that worked. Set them through set_graph_options / set_axis, " +
      "then confirm with describe_graph.",
  };
}

export interface OptionLookup {
  option: string;
  /** False only when the catalogue has never heard of this path — likely a typo. */
  known: boolean;
  /** The chart kinds where setting it changes the drawing. */
  kinds?: string[];
  example?: unknown;
  group?: string;
  /**
   * Measured as reaching no kind's drawing. Note: a question, not a conclusion — it may be an
   * option that really does nothing, or one whose prerequisite the measurement could not set up. Either way, setting it alone
   * is not expected to do anything.
   */
  deadEverywhere?: boolean;
  /** The measurement could not synthesise a value, so this option was never measured either way. */
  untestable?: boolean;
}

export interface OptionFacts {
  /** Option paths that reach some kind's drawing. */
  working: string[];
  /** Option paths measured as reaching none. */
  deadEverywhere: string[];
  /** Option paths that could not be measured at all. */
  untestable: string[];
  lookup: (option: string) => OptionLookup;
}

/** Facts about individual options — the "does X do anything?" question. */
export function optionFacts(): OptionFacts {
  const dead = DATA.deadEverywhere.map(pathOf);
  const untestable = DATA.untestable.map(pathOf);
  const deadSet = new Set(dead);
  const untestableSet = new Set(untestable);

  return {
    working: Object.keys(DATA.options),
    deadEverywhere: dead,
    untestable,
    lookup(option: string): OptionLookup {
      const raw = DATA.options[option];
      if (raw) {
        return {
          option,
          known: true,
          kinds: raw.k.map((i) => DATA.kinds[i]!),
          example: raw.ex,
          group: DATA.groups[raw.g] ?? "",
        };
      }
      // "Measured as having no effect" is a different answer from "I have never heard of it",
      // and the agent should act differently on each: stop, versus check the spelling.
      if (deadSet.has(option)) return { option, known: true, deadEverywhere: true, kinds: [] };
      if (untestableSet.has(option)) return { option, known: true, untestable: true, kinds: [] };
      return { option, known: false };
    },
  };
}
