import { readFileSync } from "node:fs";
import { expect, test } from "@playwright/test";
import { collectErrors, MadyApp } from "./app";

/**
 * One preset, every graph type, live — the real-browser twin of
 * `preset-all-kinds-roundtrip.test.ts`, driven through the app's own buttons.
 *
 * For every graph type with a gallery card: open the card as a real graph, change every setting
 * the type owns (the values come from `e2e/fixtures/preset-walk.json`, generated by the unit walk
 * from the candidate values in `optionEffects.ts`; they reach the document through the Inspector's
 * onSetPlotOptions handler, the same path a control takes), then on the Style tab press Save
 * with "Include this graph type's own settings" ticked (first type) or "+ <type>" on the preset's
 * card (every later type). Then Export… the preset and Import preset… it back, and for every type
 * open a fresh card, click the imported preset, and read every changed value back off the plot.
 *
 * The browser preview has no OS file dialogs, so the two file calls the buttons make are stubbed
 * on `window.mady`: the export's text is captured and the import hands it straight back — the
 * serialising and parsing in between are the app's own.
 */
type Walk = { kind: string; card: string; label: string; changes: { path: string[]; value: unknown; alt?: unknown }[] }[];
const WALK: Walk = JSON.parse(readFileSync(new URL("./fixtures/preset-walk.json", import.meta.url), "utf8"));

const getPath = (o: unknown, path: string[]): unknown => path.reduce<unknown>((cur, k) => (cur && typeof cur === "object" ? (cur as Record<string, unknown>)[k] : undefined), o);

test.describe("one preset carries every graph type's modified settings — live", () => {
  test("modify every type · save into one preset · export · import · apply to a fresh graph of every type", async ({ page }) => {
    test.setTimeout(30 * 60_000);
    // The 30 minutes above are for the walk (every type in the fixture, twice), not for any single click: with no limit of
    // its own, a click on a control that is not there waits out the whole test before reporting a failure
    // that 20 seconds would show.
    page.setDefaultTimeout(20_000);
    await collectErrors(page);
    await page.addInitScript(() => {
      const w = window as unknown as { mady: Record<string, unknown>; __exported?: { text: string; suggestedName: string } };
      w.mady = w.mady ?? {};
      w.mady.exportFile = async (payload: { text: string; suggestedName: string }) => { w.__exported = payload; return { ok: true, path: `C:/fake/${payload.suggestedName}.json` }; };
      w.mady.presetImport = async () => ({ ok: true, files: [{ name: "every-type.mady-preset.json", text: w.__exported?.text ?? "" }] });
    });
    const app = new MadyApp(page);
    await app.open();
    expect(WALK.length, "the fixture must cover the gallery's types").toBeGreaterThanOrEqual(40);

    const section = page.locator("details.inspsec", { hasText: "Style preset" }).first();
    const styleTab = async (): Promise<void> => {
      // The rail mounts once something in the figure is targeted. A click at a fixed pixel can hit
      // a title (the 3-D scatter's) and open its inline editor instead; click the figure's root
      // (the graph-level target) and close any editor a stray press may have opened.
      await page.keyboard.press("Escape");
      if ((await page.locator(".inspcats button").count()) === 0) {
        await page.evaluate(() => document.querySelector("svg.gfx-figure")!.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true })));
        await app.settle();
      }
      await expect(page.locator(".inspcats button", { hasText: /^Style$/ }), "the Inspector rail did not mount for this graph").toBeVisible({ timeout: 10_000 });
      await page.locator(".inspcats button", { hasText: /^Style$/ }).click();
      await app.settle();
      await page.evaluate(() => { for (const d of document.querySelectorAll<HTMLDetailsElement>("details.inspsec")) if (/Style preset/.test(d.querySelector("summary")?.textContent ?? "")) d.open = true; });
      await app.settle();
    };
    /**
     * The types a preset carries are shown behind "Manage…". The simple view is the default — a
     * card shows name, colours and the favourite star; the management row (the types it holds,
     * rename, duplicate, order, export, delete) appears only once Manage… is pressed, so `.pc-kind`
     * cannot be read off the card before that.
     * The button exists only once there is a preset, and it toggles, so this checks aria-pressed
     * rather than clicking blindly (a blind click would hide the row again on the second type).
     */
    const showManage = async (): Promise<void> => {
      const btn = section.locator('button[aria-label="Manage presets"]');
      if ((await btn.count()) === 0) return;
      if ((await btn.getAttribute("aria-pressed")) === "true") return;
      await btn.click();
      await app.settle();
    };
    const openFreshCard = async (title: string): Promise<string> => {
      await app.openGallery();
      const card = page.locator(".gallerycard").filter({ has: page.locator(".gallerycard-h", { hasText: new RegExp(`^${title.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`) }) }).first();
      await card.scrollIntoViewIfNeeded();
      await card.click();
      await page.waitForSelector("svg.gfx-figure", { timeout: 30_000 });
      await app.settle();
      return app.activePlotId();
    };
    /** Set values on the active plot through the Inspector's handler, nested paths merged. */
    const setValues = async (id: string, values: { path: string[]; value: unknown }[]): Promise<void> => {
      for (const c of values) {
        const plot = (await app.plot(id))!;
        const patch: Record<string, unknown> = {};
        if (c.path.length === 1) patch[c.path[0]!] = c.value;
        else patch[c.path[0]!] = { ...((plot[c.path[0]!] as Record<string, unknown> | undefined) ?? {}), [c.path[1]!]: c.value };
        await app.setPlotOptions(patch);
      }
      const after = (await app.plot(id))!;
      for (const c of values) expect(getPath(after, c.path), `${id}: ${c.path.join(".")} did not take`).toEqual(c.value);
    };
    // A gallery card reopens the graph made from it (by design: a card never forks), so pass 2 first
    // moves every changed setting to a different value (the fixture's `alt`) — the preset must
    // then bring each one back, which is a sharper check than a fresh graph would be.

    // ── 1. every type: modify, then save into the one preset ─────────────────────────────
    const PRESET = "Every type";
    for (const [i, w] of WALK.entries()) {
      console.log(`[walk 1/2] ${i + 1}/${WALK.length} ${w.kind}`);
      const id = await openFreshCard(w.card);
      await setValues(id, w.changes);
      await styleTab();
      await showManage();
      if (i === 0) {
        const tick = section.locator('input[aria-label="Include this graph type\'s own settings"]');
        await expect(tick).toBeChecked();
        await page.locator('input[aria-label="Preset name"]').fill(PRESET);
        await section.locator("button", { hasText: /^Save$/ }).first().click();
      } else {
        const add = section.locator(`button[aria-label="Add ${w.label} settings to ${PRESET}"]`);
        await expect(add, `${w.kind}: "+ ${w.label}" must be offered and enabled`).toBeEnabled();
        await add.click();
      }
      await app.settle();
      await showManage(); // the first Save is what creates the preset, and with it the Manage… button
      const pills = (await section.locator(".pc-row", { hasText: PRESET }).first().locator(".pc-kind").allTextContents())
        // The pill for the open graph’s type ends in a check mark — that marks its state, not its name.
        .map((t) => t.replace(/\s*✓\s*$/, "").trim());
      expect(pills, `${w.kind}: the card must now list ${w.label}`).toContain(w.label);
    }
    const stored = await page.evaluate(() => JSON.parse(localStorage.getItem("mady.userPresets.v1") ?? "[]") as { name: string; kinds?: Record<string, unknown> }[]);
    const savedRec = stored.find((p) => p.name === PRESET)!;
    for (const w of WALK) for (const c of w.changes) expect(getPath(savedRec.kinds?.[w.kind], c.path), `${w.kind}: the saved preset lost ${c.path.join(".")}`).toEqual(c.value);

    // ── 2. export the preset, import it back ─────────────────────────────────────────────
    /**
     * Export lives in the card's "More actions" menu, with Rename / Duplicate / Types… / Delete.
     * The item carries the aria-label "Export <preset>", but it is not in the DOM until the menu
     * is opened.
     */
    await showManage();
    await section.locator(`button[aria-label="More actions for ${PRESET}"]`).click();
    await app.settle();
    // Caution: click "More actions" once only. The button toggles, so a second click closes the menu again.
    await section.locator(`[role="menu"][aria-label="Actions for ${PRESET}"] button[aria-label="Export ${PRESET}"]`).click();
    await expect(section).toContainText(`Exported "${PRESET}".`);
    const file = await page.evaluate(() => (window as unknown as { __exported?: { text: string } }).__exported?.text ?? "");
    expect(JSON.parse(file).format).toBe("mady-preset");
    await section.locator("button", { hasText: /^Import preset…$/ }).click();
    await expect(section).toContainText(`Imported "${PRESET} (2)".`);
    const IMPORTED = `${PRESET} (2)`;
    const stored2 = await page.evaluate(() => JSON.parse(localStorage.getItem("mady.userPresets.v1") ?? "[]") as { id: string; name: string; kinds?: Record<string, unknown> }[]);
    const orig = stored2.find((p) => p.name === PRESET)!;
    const imp = stored2.find((p) => p.name === IMPORTED)!;
    expect(imp.id).not.toBe(orig.id);
    expect(imp.kinds).toEqual(orig.kinds);

    // ── 3. every type: a fresh graph takes the imported preset, every change lands ───────
    for (const w of WALK) {
      console.log(`[walk 2/2] ${w.kind}`);
      const id = await openFreshCard(w.card);
      await setValues(id, w.changes.filter((c) => "alt" in c).map((c) => ({ path: c.path, value: c.alt })));
      const before = (await app.plot(id))!;
      const untouched = w.changes.filter((c) => JSON.stringify(getPath(before, c.path)) !== JSON.stringify(c.value));
      expect(untouched.length, `${w.kind}: the graph already has every modified value — the apply could not be seen`).toBeGreaterThan(0);
      await styleTab();
      await section.locator("button.presetcard", { hasText: IMPORTED }).first().click();
      await app.settle();
      const after = (await app.plot(id))!;
      for (const c of w.changes) expect(getPath(after, c.path), `${w.kind}: after applying "${IMPORTED}", ${c.path.join(".")} is not the modified value`).toEqual(c.value);
    }
    expect(await app.consoleErrors()).toEqual([]);
  });
});
