// @vitest-environment node
import { describe, expect, it } from "vitest";
import type { Lineage, Project } from "@mady/core";
import { buildReproBundle } from "./reproBundle";

const lineage: Lineage = {
  nodes: [
    { kind: "table", id: "t1", name: "Dose data", status: "ok" },
    { kind: "table", id: "t2", name: "Normalized", status: "stale" },
    { kind: "analysis", id: "a1", name: "Unpaired t test", status: "ok" },
    { kind: "plot", id: "p1", name: "Dose curve", status: "ok" },
  ],
  edges: [
    { from: "t1", to: "t2", relation: "derives" },
    { from: "t1", to: "a1", relation: "analyzes" },
    { from: "t1", to: "p1", relation: "plots" },
  ],
};

const project = {
  tables: [
    { id: "t1", name: "Dose data" },
    { id: "t2", name: "Normalized" },
  ],
  plots: [{ id: "p1", name: "Dose curve" }],
  analyses: [
    {
      id: "a1",
      name: "Unpaired t test",
      method: "ttest",
      source: "t1",
      status: "ok",
      params: { columns: ["c1", "c2"], variant: "welch", conf: 0.95 },
      result: {
        method: "ttest",
        title: "Unpaired t test (Welch)",
        terms: [{ term: "Difference", statistic: 3.42, df: 18, p: 0.003 }],
        glance: { p: 0.003, cohens_d: 1.2 },
        summary: "Group A differs from group B.",
        cite: "Welch, B. L. (1947)",
        assumptions: ["Assumes the two samples are roughly normal."],
      },
    },
  ],
  layouts: [],
  workspace: { folders: [{ id: "f1", name: "My Project" }], loose: [] },
} as unknown as Project;

const opts = { generatedAt: "2026-01-01T00:00:00Z", appVersion: "v1.2.3" };

describe("buildReproBundle", () => {
  const md = buildReproBundle(project, lineage, opts);

  it("titles the bundle from the project folder + stamps it", () => {
    expect(md).toContain("# Reproducibility bundle — My Project");
    expect(md).toContain("_Generated by MadY on 2026-01-01T00:00:00Z · v1.2.3._");
  });

  it("reports the object counts", () => {
    expect(md).toContain("- Data tables: 2");
    expect(md).toContain("- Analyses: 1");
    expect(md).toContain("- Graphs: 1");
  });

  it("renders the provenance: roots + each derived sheet's sources + stale flag", () => {
    expect(md).toContain("**Source data:** Dose data");
    expect(md).toContain("- **Normalized** (table) ← Dose data _(stale — re-run to refresh)_");
    expect(md).toContain("- **Unpaired t test** (analysis) ← Dose data");
    expect(md).toContain("- **Dose curve** (plot) ← Dose data");
  });

  it("details each analysis (method, settings, key results, interpretation, cite)", () => {
    expect(md).toContain("### Unpaired t test");
    expect(md).toContain("- **Method:** Unpaired t test (Welch) (`ttest/welch`)");
    expect(md).toContain("- **Source data:** Dose data");
    expect(md).toContain('- **Settings:** `{"variant":"welch","conf":0.95}`');
    expect(md).toContain("- **Key results:** p = 0.003");
    expect(md).toContain("- **Interpretation:** Group A differs from group B.");
    expect(md).toContain("- **Assumptions:** Assumes the two samples are roughly normal.");
    expect(md).toContain("- **Citation:** Welch, B. L. (1947)");
  });

  it("includes a paste-ready Methods & Results (draft) section from the prose drafter", () => {
    expect(md).toContain("## Methods & Results (draft)");
    expect(md).toContain(
      "**Methods.** Unpaired t test (Welch) was used to compare the means of the two groups (data: “Dose data”). " +
        "Assumes the two samples are roughly normal. " +
        "Effect size is reported as Cohen's d (with Hedges' g) with a 95% confidence interval. Welch, B. L. (1947). " +
        "Statistical analysis was performed in MadY. " +
        "A two-sided P value below 0.05 was considered statistically significant.",
    );
    expect(md).toContain(
      "- _Unpaired t test:_ Group A differs from group B (t(18) = 3.42, p = 0.003, Cohen's d = 1.2).",
    );
    // The stack detail is a footnote under the draft, never in the Methods body.
    expect(md).toContain("_Footnote: MadY performs its statistical computations using NumPy and SciPy._");
  });

  it("embeds a runnable Python script + a machine-readable JSON manifest", () => {
    expect(md).toContain("## Reproducible analysis script (Python)");
    expect(md).toContain("```python");
    expect(md).toContain("```json");
    expect(md).toContain('"tool": "MadY"');
    expect(md).toContain('"title": "My Project"');
    expect(md).toContain('"method": "ttest"');
    // the lineage is embedded in the manifest
    expect(md).toContain('"kind": "analysis"');
  });

  it("notes the environment", () => {
    expect(md).toContain("- Statistics engine: Python — NumPy, SciPy + statsmodels");
    expect(md).toContain("- Application: MadY (v1.2.3)");
  });

  it("handles an empty project gracefully", () => {
    const empty = {
      tables: [],
      plots: [],
      analyses: [],
      layouts: [],
      workspace: { folders: [], loose: [] },
    } as unknown as Project;
    const out = buildReproBundle(empty, { nodes: [], edges: [] });
    expect(out).toContain("# Reproducibility bundle — MadY project");
    expect(out).toContain("_This project has no analyses yet._");
    expect(out).toContain("_No analyses or graphs yet._");
    // Nothing has run → no draft-prose section at all.
    expect(out).not.toContain("## Methods & Results (draft)");
  });
});
