/**
 * Reproducibility bundle export.
 *
 * Assembles a single self-describing **Markdown** document that captures everything
 * needed to reproduce a project's results from the raw data:
 *   1. an overview + the provenance/lineage DAG (what derives from what),
 *   2. every analysis's method, parameters, key results and interpretation,
 *   3. a runnable **Python** script (numpy/scipy, plus statsmodels and others where a method needs them) that recomputes the numbers, and
 *   4. a machine-readable **JSON manifest**.
 *
 * One openable, greppable, archivable file — no external tooling to read it. Pure +
 * DOM-free → unit-testable; the timestamp/version are injected so it stays deterministic.
 */
import type { Analysis, AnalysisParams, Lineage, Project } from "@mady/core";
import { buildPythonScript } from "./scriptExport";
import { keyMetricLine } from "./analysisExport";
import { draftProjectMethods } from "./methodsProse";

export interface ReproBundleOptions {
  /** Human title (defaults to the first project folder's name). */
  title?: string | undefined;
  /** ISO timestamp of when the bundle was generated (injected for determinism). */
  generatedAt?: string | undefined;
  /** App build stamp (version · commit · time). */
  appVersion?: string | undefined;
}

/** The analysis parameters worth showing a human (ids/internal fields dropped). */
function humanParams(params: AnalysisParams): Record<string, unknown> {
  const skip = new Set(["columns", "groupBy"]);
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(params)) {
    if (skip.has(k) || v === undefined || v === null) continue;
    out[k] = v;
  }
  return out;
}

/** "Method (`id`/variant)" heading for one analysis. */
function methodLabel(a: Analysis): string {
  const title = a.result?.title || a.name;
  const idPart = a.params.variant ? `${a.method}/${a.params.variant}` : a.method;
  return `${title} (\`${idPart}\`)`;
}

/** The provenance lines: every derived sheet and the sources it descends from. */
function lineageSection(lineage: Lineage): string[] {
  const nameOf = new Map(lineage.nodes.map((n) => [n.id, n]));
  const parents = new Map<string, string[]>();
  for (const e of lineage.edges) {
    const arr = parents.get(e.to);
    if (arr) arr.push(e.from);
    else parents.set(e.to, [e.from]);
  }
  const roots = lineage.nodes.filter((n) => !parents.has(n.id));
  const derived = lineage.nodes.filter((n) => parents.has(n.id));
  const lines: string[] = [];
  if (roots.length) {
    lines.push(`**Source data:** ${roots.map((n) => `${n.name}`).join(", ")}`, "");
  }
  for (const n of derived) {
    const src = (parents.get(n.id) ?? [])
      .map((id) => nameOf.get(id)?.name ?? id)
      .join(", ");
    const stale = n.status === "stale" ? " _(stale — re-run to refresh)_" : n.status === "error" ? " _(error)_" : "";
    lines.push(`- **${n.name}** (${n.kind}) ← ${src}${stale}`);
  }
  if (!lines.length) lines.push("_No analyses or graphs yet._");
  return lines;
}

/** The machine-readable manifest object (serialised to JSON in the bundle). */
function manifest(project: Project, lineage: Lineage, opts: ReproBundleOptions): unknown {
  return {
    tool: "MadY",
    app: opts.appVersion ?? null,
    generatedAt: opts.generatedAt ?? null,
    title: opts.title ?? project.workspace.folders[0]?.name ?? "MadY project",
    counts: {
      tables: project.tables.length,
      analyses: project.analyses.length,
      plots: project.plots.length,
      layouts: project.layouts?.length ?? 0,
    },
    analyses: project.analyses.map((a) => ({
      id: a.id,
      name: a.name,
      method: a.method,
      variant: a.params.variant ?? null,
      source: a.source,
      sourceName: project.tables.find((t) => t.id === a.source)?.name ?? null,
      status: a.status,
      params: humanParams(a.params),
      glance: a.result?.glance ?? null,
    })),
    lineage,
  };
}

/**
 * Build the full reproducibility bundle as a Markdown string.
 */
export function buildReproBundle(project: Project, lineage: Lineage, opts: ReproBundleOptions = {}): string {
  const title = opts.title ?? project.workspace.folders[0]?.name ?? "MadY project";
  const stamp = [opts.generatedAt ? `on ${opts.generatedAt}` : null, opts.appVersion]
    .filter(Boolean)
    .join(" · ");

  const out: string[] = [];
  out.push(`# Reproducibility bundle — ${title}`, "");
  out.push(`_Generated by MadY${stamp ? ` ${stamp}` : ""}._`, "");
  out.push(
    "This file captures the provenance of every result, the exact method and parameters used,",
    "the headline numbers, and a runnable Python script that recomputes them from the raw data —",
    "so the analyses can be reproduced and reviewed without MadY.",
    "",
  );

  // Overview
  out.push("## Overview", "");
  out.push(`- Data tables: ${project.tables.length}`);
  out.push(`- Analyses: ${project.analyses.length}`);
  out.push(`- Graphs: ${project.plots.length}`);
  out.push(`- Figures: ${project.layouts?.length ?? 0}`, "");

  // Provenance / lineage
  out.push("## Provenance", "");
  out.push(...lineageSection(lineage), "");

  // Draft Methods & Results prose — paste-ready, statistically exact (reuses the
  // per-analysis drafter); the detailed per-analysis breakdown follows below.
  const prose = draftProjectMethods(project);
  if (prose) {
    out.push("## Methods & Results (draft)", "");
    out.push(
      "_Publication-style prose assembled from the analyses below. The numbers come straight",
      "from the validated engine output, but review the wording before use._",
      "",
    );
    out.push(`**Methods.** ${prose.methods}`, "");
    out.push("**Results.**", "");
    for (const r of prose.results) out.push(`- _${r.name}:_ ${r.results}`);
    out.push("");
    out.push(`_Footnote: ${prose.footnote}_`, "");
  }

  // Analyses
  out.push("## Analyses", "");
  if (project.analyses.length === 0) {
    out.push("_This project has no analyses yet._", "");
  } else {
    for (const a of project.analyses) {
      const r = a.result;
      out.push(`### ${a.name}`, "");
      out.push(`- **Method:** ${methodLabel(a)}`);
      out.push(`- **Source data:** ${project.tables.find((t) => t.id === a.source)?.name ?? a.source}`);
      const params = humanParams(a.params);
      if (Object.keys(params).length) out.push(`- **Settings:** \`${JSON.stringify(params)}\``);
      if (r) {
        const key = keyMetricLine(r);
        if (key) out.push(`- **Key results:** ${key}`);
        if (r.summary) out.push(`- **Interpretation:** ${r.summary}`);
        if (r.assumptions?.length) out.push(`- **Assumptions:** ${r.assumptions.join(" ")}`);
        if (r.cite) out.push(`- **Citation:** ${r.cite}`);
      } else {
        out.push(`- _Not yet run (${a.status})._`);
      }
      out.push("");
    }
  }

  // Reproducible script
  out.push("## Reproducible analysis script (Python)", "");
  out.push("Re-runs each analysis from its source data using numpy + scipy (plus pandas, statsmodels, lifelines or scikit-learn where a method needs them).", "");
  out.push("```python", buildPythonScript(project).replace(/\n+$/, ""), "```", "");

  // Manifest
  out.push("## Machine-readable manifest", "");
  out.push("```json", JSON.stringify(manifest(project, lineage, opts), null, 2), "```", "");

  // Environment
  out.push("## Environment", "");
  out.push("- Application: MadY" + (opts.appVersion ? ` (${opts.appVersion})` : ""));
  out.push("- Statistics engine: Python — NumPy, SciPy + statsmodels");
  if (opts.generatedAt) out.push(`- Generated: ${opts.generatedAt}`);
  out.push("");

  return out.join("\n");
}
